### PR TITLE
Added initial exit codes support

### PR DESCRIPTION
**Pull request by etki**
Hi, i've added exit codes support (1 - argument parsing error, 2 - runtime error), though i'm not sure i'm doing everything clean enough and AllureCommand casting is erm legal; also, you may want to change exit codes to introduce some clean API. Code review (telling me that i've done everything ok or pointing me to unsafe places) would be appreciated.

References #28.

### CODE REVIEW

**Comment by vania-pooh** [comment]
@eroshenkoam what do you think?

**Comment by kshepitko** [comment]
Our application uses CLI tool to generate HTML reports, so currently we depend heavily on exit codes to react on any problems during report generation, like NPE described in #33 

Any plans on merging these changes?

**Comment by vania-pooh** [comment]
@kshepitko please send a new PR.

**Comment by etki** [comment]
@vania-pooh @kshepitko i may devote some time to recreate this PR regarding accepted PRs on weekend (there are only couple of lines to correct, though).

**Comment by kshepitko** [comment]
@etki this would be much appreciated!!

**Comment by etki** [comment]
@vania-pooh @kshepitko Should be fixed by now. Current version introduced little architecture flaw which, i guess, can't be solved without proper error support; changed generic error code from 2 to 127.

**Comment by vania-pooh** [comment]
@eroshenkoam please merge if that's ok.

**Comment by etki** [comment]
Added enum-based exit codes, sorry for huge delays on such simple task. Tell me if anything else needs to be fixed.
ping @eroshenkoam

**Comment by vania-pooh** [comment]
@etki thank you for contribution.

**Pull request merged**
